spring.application.name=PrintEase

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/printease
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=${JWT_SECRET:a_very_long_secret_key_for_jwt_signing_which_needs_to_be_at_least_256_bits_for_hmac_sha}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Paystack Config
paystack.secret-key=${PAYSTACK_SECRET_KEY:sk_test_0cd4d796090482a8dfce31c432ff0196eeb2eff3}

# File Upload Configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB